// Code generated by ent, DO NOT EDIT.

package deepingtalk

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the deepingtalk type in the database.
	Label = "deeping_talk"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTalkVideo holds the string denoting the talk_video field in the database.
	FieldTalkVideo = "talk_video"
	// FieldPlayableVideo holds the string denoting the playable_video field in the database.
	FieldPlayableVideo = "playable_video"
	// Table holds the table name of the deepingtalk in the database.
	Table = "deepingtalk_deepingtalk"
)

// Columns holds all SQL columns for deepingtalk fields.
var Columns = []string{
	FieldID,
	FieldTalkVideo,
	FieldPlayableVideo,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the DeepingTalk queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTalkVideo orders the results by the talk_video field.
func ByTalkVideo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTalkVideo, opts...).ToFunc()
}

// ByPlayableVideo orders the results by the playable_video field.
func ByPlayableVideo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlayableVideo, opts...).ToFunc()
}
