// Code generated by ent, DO NOT EDIT.

package productreview

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the productreview type in the database.
	Label = "product_review"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPlayableVideo holds the string denoting the playable_video field in the database.
	FieldPlayableVideo = "playable_video"
	// FieldReviewVideo holds the string denoting the review_video field in the database.
	FieldReviewVideo = "review_video"
	// Table holds the table name of the productreview in the database.
	Table = "deepingreview_productreview"
)

// Columns holds all SQL columns for productreview fields.
var Columns = []string{
	FieldID,
	FieldPlayableVideo,
	FieldReviewVideo,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the ProductReview queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPlayableVideo orders the results by the playable_video field.
func ByPlayableVideo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlayableVideo, opts...).ToFunc()
}

// ByReviewVideo orders the results by the review_video field.
func ByReviewVideo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReviewVideo, opts...).ToFunc()
}
