// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ProductProductvideoColumns holds the columns for the "product_productvideo" table.
	ProductProductvideoColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "url", Type: field.TypeString},
	}
	// ProductProductvideoTable holds the schema information for the "product_productvideo" table.
	ProductProductvideoTable = &schema.Table{
		Name:       "product_productvideo",
		Columns:    ProductProductvideoColumns,
		PrimaryKey: []*schema.Column{ProductProductvideoColumns[0]},
	}
	// AccountUservideoColumns holds the columns for the "account_uservideo" table.
	AccountUservideoColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "video_id", Type: field.TypeInt},
		{Name: "video_url", Type: field.TypeString},
	}
	// AccountUservideoTable holds the schema information for the "account_uservideo" table.
	AccountUservideoTable = &schema.Table{
		Name:       "account_uservideo",
		Columns:    AccountUservideoColumns,
		PrimaryKey: []*schema.Column{AccountUservideoColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ProductProductvideoTable,
		AccountUservideoTable,
	}
)

func init() {
	ProductProductvideoTable.Annotation = &entsql.Annotation{
		Table: "product_productvideo",
	}
	AccountUservideoTable.Annotation = &entsql.Annotation{
		Table: "account_uservideo",
	}
}
