// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kvngho/vimeovideoconverter/internal/infrastructure/persistence/ent/deepingtalk"
	"github.com/kvngho/vimeovideoconverter/internal/infrastructure/persistence/ent/predicate"
)

// DeepingTalkDelete is the builder for deleting a DeepingTalk entity.
type DeepingTalkDelete struct {
	config
	hooks    []Hook
	mutation *DeepingTalkMutation
}

// Where appends a list predicates to the DeepingTalkDelete builder.
func (dtd *DeepingTalkDelete) Where(ps ...predicate.DeepingTalk) *DeepingTalkDelete {
	dtd.mutation.Where(ps...)
	return dtd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (dtd *DeepingTalkDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, dtd.sqlExec, dtd.mutation, dtd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (dtd *DeepingTalkDelete) ExecX(ctx context.Context) int {
	n, err := dtd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (dtd *DeepingTalkDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(deepingtalk.Table, sqlgraph.NewFieldSpec(deepingtalk.FieldID, field.TypeInt))
	if ps := dtd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, dtd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	dtd.mutation.done = true
	return affected, err
}

// DeepingTalkDeleteOne is the builder for deleting a single DeepingTalk entity.
type DeepingTalkDeleteOne struct {
	dtd *DeepingTalkDelete
}

// Where appends a list predicates to the DeepingTalkDelete builder.
func (dtdo *DeepingTalkDeleteOne) Where(ps ...predicate.DeepingTalk) *DeepingTalkDeleteOne {
	dtdo.dtd.mutation.Where(ps...)
	return dtdo
}

// Exec executes the deletion query.
func (dtdo *DeepingTalkDeleteOne) Exec(ctx context.Context) error {
	n, err := dtdo.dtd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{deepingtalk.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (dtdo *DeepingTalkDeleteOne) ExecX(ctx context.Context) {
	if err := dtdo.Exec(ctx); err != nil {
		panic(err)
	}
}
