// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kvngho/vimeovideoconverter/internal/infrastructure/persistence/ent/productvideo"
)

// ProductVideoCreate is the builder for creating a ProductVideo entity.
type ProductVideoCreate struct {
	config
	mutation *ProductVideoMutation
	hooks    []Hook
}

// SetURL sets the "url" field.
func (pvc *ProductVideoCreate) SetURL(s string) *ProductVideoCreate {
	pvc.mutation.SetURL(s)
	return pvc
}

// SetPlayableVideo sets the "playable_video" field.
func (pvc *ProductVideoCreate) SetPlayableVideo(s string) *ProductVideoCreate {
	pvc.mutation.SetPlayableVideo(s)
	return pvc
}

// Mutation returns the ProductVideoMutation object of the builder.
func (pvc *ProductVideoCreate) Mutation() *ProductVideoMutation {
	return pvc.mutation
}

// Save creates the ProductVideo in the database.
func (pvc *ProductVideoCreate) Save(ctx context.Context) (*ProductVideo, error) {
	return withHooks(ctx, pvc.sqlSave, pvc.mutation, pvc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (pvc *ProductVideoCreate) SaveX(ctx context.Context) *ProductVideo {
	v, err := pvc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pvc *ProductVideoCreate) Exec(ctx context.Context) error {
	_, err := pvc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pvc *ProductVideoCreate) ExecX(ctx context.Context) {
	if err := pvc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pvc *ProductVideoCreate) check() error {
	if _, ok := pvc.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "ProductVideo.url"`)}
	}
	if _, ok := pvc.mutation.PlayableVideo(); !ok {
		return &ValidationError{Name: "playable_video", err: errors.New(`ent: missing required field "ProductVideo.playable_video"`)}
	}
	return nil
}

func (pvc *ProductVideoCreate) sqlSave(ctx context.Context) (*ProductVideo, error) {
	if err := pvc.check(); err != nil {
		return nil, err
	}
	_node, _spec := pvc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pvc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	pvc.mutation.id = &_node.ID
	pvc.mutation.done = true
	return _node, nil
}

func (pvc *ProductVideoCreate) createSpec() (*ProductVideo, *sqlgraph.CreateSpec) {
	var (
		_node = &ProductVideo{config: pvc.config}
		_spec = sqlgraph.NewCreateSpec(productvideo.Table, sqlgraph.NewFieldSpec(productvideo.FieldID, field.TypeInt))
	)
	if value, ok := pvc.mutation.URL(); ok {
		_spec.SetField(productvideo.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := pvc.mutation.PlayableVideo(); ok {
		_spec.SetField(productvideo.FieldPlayableVideo, field.TypeString, value)
		_node.PlayableVideo = value
	}
	return _node, _spec
}

// ProductVideoCreateBulk is the builder for creating many ProductVideo entities in bulk.
type ProductVideoCreateBulk struct {
	config
	err      error
	builders []*ProductVideoCreate
}

// Save creates the ProductVideo entities in the database.
func (pvcb *ProductVideoCreateBulk) Save(ctx context.Context) ([]*ProductVideo, error) {
	if pvcb.err != nil {
		return nil, pvcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(pvcb.builders))
	nodes := make([]*ProductVideo, len(pvcb.builders))
	mutators := make([]Mutator, len(pvcb.builders))
	for i := range pvcb.builders {
		func(i int, root context.Context) {
			builder := pvcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProductVideoMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pvcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pvcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pvcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pvcb *ProductVideoCreateBulk) SaveX(ctx context.Context) []*ProductVideo {
	v, err := pvcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pvcb *ProductVideoCreateBulk) Exec(ctx context.Context) error {
	_, err := pvcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pvcb *ProductVideoCreateBulk) ExecX(ctx context.Context) {
	if err := pvcb.Exec(ctx); err != nil {
		panic(err)
	}
}
