// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kvngho/vimeovideoconverter/internal/infrastructure/persistence/ent/predicate"
	"github.com/kvngho/vimeovideoconverter/internal/infrastructure/persistence/ent/productvideo"
)

// ProductVideoQuery is the builder for querying ProductVideo entities.
type ProductVideoQuery struct {
	config
	ctx        *QueryContext
	order      []productvideo.OrderOption
	inters     []Interceptor
	predicates []predicate.ProductVideo
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ProductVideoQuery builder.
func (pvq *ProductVideoQuery) Where(ps ...predicate.ProductVideo) *ProductVideoQuery {
	pvq.predicates = append(pvq.predicates, ps...)
	return pvq
}

// Limit the number of records to be returned by this query.
func (pvq *ProductVideoQuery) Limit(limit int) *ProductVideoQuery {
	pvq.ctx.Limit = &limit
	return pvq
}

// Offset to start from.
func (pvq *ProductVideoQuery) Offset(offset int) *ProductVideoQuery {
	pvq.ctx.Offset = &offset
	return pvq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (pvq *ProductVideoQuery) Unique(unique bool) *ProductVideoQuery {
	pvq.ctx.Unique = &unique
	return pvq
}

// Order specifies how the records should be ordered.
func (pvq *ProductVideoQuery) Order(o ...productvideo.OrderOption) *ProductVideoQuery {
	pvq.order = append(pvq.order, o...)
	return pvq
}

// First returns the first ProductVideo entity from the query.
// Returns a *NotFoundError when no ProductVideo was found.
func (pvq *ProductVideoQuery) First(ctx context.Context) (*ProductVideo, error) {
	nodes, err := pvq.Limit(1).All(setContextOp(ctx, pvq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{productvideo.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (pvq *ProductVideoQuery) FirstX(ctx context.Context) *ProductVideo {
	node, err := pvq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ProductVideo ID from the query.
// Returns a *NotFoundError when no ProductVideo ID was found.
func (pvq *ProductVideoQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = pvq.Limit(1).IDs(setContextOp(ctx, pvq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{productvideo.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (pvq *ProductVideoQuery) FirstIDX(ctx context.Context) int {
	id, err := pvq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ProductVideo entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ProductVideo entity is found.
// Returns a *NotFoundError when no ProductVideo entities are found.
func (pvq *ProductVideoQuery) Only(ctx context.Context) (*ProductVideo, error) {
	nodes, err := pvq.Limit(2).All(setContextOp(ctx, pvq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{productvideo.Label}
	default:
		return nil, &NotSingularError{productvideo.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (pvq *ProductVideoQuery) OnlyX(ctx context.Context) *ProductVideo {
	node, err := pvq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ProductVideo ID in the query.
// Returns a *NotSingularError when more than one ProductVideo ID is found.
// Returns a *NotFoundError when no entities are found.
func (pvq *ProductVideoQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = pvq.Limit(2).IDs(setContextOp(ctx, pvq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{productvideo.Label}
	default:
		err = &NotSingularError{productvideo.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (pvq *ProductVideoQuery) OnlyIDX(ctx context.Context) int {
	id, err := pvq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ProductVideos.
func (pvq *ProductVideoQuery) All(ctx context.Context) ([]*ProductVideo, error) {
	ctx = setContextOp(ctx, pvq.ctx, ent.OpQueryAll)
	if err := pvq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ProductVideo, *ProductVideoQuery]()
	return withInterceptors[[]*ProductVideo](ctx, pvq, qr, pvq.inters)
}

// AllX is like All, but panics if an error occurs.
func (pvq *ProductVideoQuery) AllX(ctx context.Context) []*ProductVideo {
	nodes, err := pvq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ProductVideo IDs.
func (pvq *ProductVideoQuery) IDs(ctx context.Context) (ids []int, err error) {
	if pvq.ctx.Unique == nil && pvq.path != nil {
		pvq.Unique(true)
	}
	ctx = setContextOp(ctx, pvq.ctx, ent.OpQueryIDs)
	if err = pvq.Select(productvideo.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (pvq *ProductVideoQuery) IDsX(ctx context.Context) []int {
	ids, err := pvq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (pvq *ProductVideoQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, pvq.ctx, ent.OpQueryCount)
	if err := pvq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, pvq, querierCount[*ProductVideoQuery](), pvq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (pvq *ProductVideoQuery) CountX(ctx context.Context) int {
	count, err := pvq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (pvq *ProductVideoQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, pvq.ctx, ent.OpQueryExist)
	switch _, err := pvq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (pvq *ProductVideoQuery) ExistX(ctx context.Context) bool {
	exist, err := pvq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ProductVideoQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (pvq *ProductVideoQuery) Clone() *ProductVideoQuery {
	if pvq == nil {
		return nil
	}
	return &ProductVideoQuery{
		config:     pvq.config,
		ctx:        pvq.ctx.Clone(),
		order:      append([]productvideo.OrderOption{}, pvq.order...),
		inters:     append([]Interceptor{}, pvq.inters...),
		predicates: append([]predicate.ProductVideo{}, pvq.predicates...),
		// clone intermediate query.
		sql:  pvq.sql.Clone(),
		path: pvq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		URL string `json:"url,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ProductVideo.Query().
//		GroupBy(productvideo.FieldURL).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (pvq *ProductVideoQuery) GroupBy(field string, fields ...string) *ProductVideoGroupBy {
	pvq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ProductVideoGroupBy{build: pvq}
	grbuild.flds = &pvq.ctx.Fields
	grbuild.label = productvideo.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		URL string `json:"url,omitempty"`
//	}
//
//	client.ProductVideo.Query().
//		Select(productvideo.FieldURL).
//		Scan(ctx, &v)
func (pvq *ProductVideoQuery) Select(fields ...string) *ProductVideoSelect {
	pvq.ctx.Fields = append(pvq.ctx.Fields, fields...)
	sbuild := &ProductVideoSelect{ProductVideoQuery: pvq}
	sbuild.label = productvideo.Label
	sbuild.flds, sbuild.scan = &pvq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ProductVideoSelect configured with the given aggregations.
func (pvq *ProductVideoQuery) Aggregate(fns ...AggregateFunc) *ProductVideoSelect {
	return pvq.Select().Aggregate(fns...)
}

func (pvq *ProductVideoQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range pvq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, pvq); err != nil {
				return err
			}
		}
	}
	for _, f := range pvq.ctx.Fields {
		if !productvideo.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if pvq.path != nil {
		prev, err := pvq.path(ctx)
		if err != nil {
			return err
		}
		pvq.sql = prev
	}
	return nil
}

func (pvq *ProductVideoQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ProductVideo, error) {
	var (
		nodes = []*ProductVideo{}
		_spec = pvq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ProductVideo).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ProductVideo{config: pvq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, pvq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (pvq *ProductVideoQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := pvq.querySpec()
	_spec.Node.Columns = pvq.ctx.Fields
	if len(pvq.ctx.Fields) > 0 {
		_spec.Unique = pvq.ctx.Unique != nil && *pvq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, pvq.driver, _spec)
}

func (pvq *ProductVideoQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(productvideo.Table, productvideo.Columns, sqlgraph.NewFieldSpec(productvideo.FieldID, field.TypeInt))
	_spec.From = pvq.sql
	if unique := pvq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if pvq.path != nil {
		_spec.Unique = true
	}
	if fields := pvq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, productvideo.FieldID)
		for i := range fields {
			if fields[i] != productvideo.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := pvq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := pvq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := pvq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := pvq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (pvq *ProductVideoQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(pvq.driver.Dialect())
	t1 := builder.Table(productvideo.Table)
	columns := pvq.ctx.Fields
	if len(columns) == 0 {
		columns = productvideo.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if pvq.sql != nil {
		selector = pvq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if pvq.ctx.Unique != nil && *pvq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range pvq.predicates {
		p(selector)
	}
	for _, p := range pvq.order {
		p(selector)
	}
	if offset := pvq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := pvq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ProductVideoGroupBy is the group-by builder for ProductVideo entities.
type ProductVideoGroupBy struct {
	selector
	build *ProductVideoQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pvgb *ProductVideoGroupBy) Aggregate(fns ...AggregateFunc) *ProductVideoGroupBy {
	pvgb.fns = append(pvgb.fns, fns...)
	return pvgb
}

// Scan applies the selector query and scans the result into the given value.
func (pvgb *ProductVideoGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pvgb.build.ctx, ent.OpQueryGroupBy)
	if err := pvgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProductVideoQuery, *ProductVideoGroupBy](ctx, pvgb.build, pvgb, pvgb.build.inters, v)
}

func (pvgb *ProductVideoGroupBy) sqlScan(ctx context.Context, root *ProductVideoQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(pvgb.fns))
	for _, fn := range pvgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*pvgb.flds)+len(pvgb.fns))
		for _, f := range *pvgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*pvgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pvgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ProductVideoSelect is the builder for selecting fields of ProductVideo entities.
type ProductVideoSelect struct {
	*ProductVideoQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (pvs *ProductVideoSelect) Aggregate(fns ...AggregateFunc) *ProductVideoSelect {
	pvs.fns = append(pvs.fns, fns...)
	return pvs
}

// Scan applies the selector query and scans the result into the given value.
func (pvs *ProductVideoSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pvs.ctx, ent.OpQuerySelect)
	if err := pvs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProductVideoQuery, *ProductVideoSelect](ctx, pvs.ProductVideoQuery, pvs, pvs.inters, v)
}

func (pvs *ProductVideoSelect) sqlScan(ctx context.Context, root *ProductVideoQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(pvs.fns))
	for _, fn := range pvs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*pvs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pvs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
