// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kvngho/vimeovideoconverter/internal/infrastructure/persistence/ent/predicate"
	"github.com/kvngho/vimeovideoconverter/internal/infrastructure/persistence/ent/productvideo"
)

// ProductVideoDelete is the builder for deleting a ProductVideo entity.
type ProductVideoDelete struct {
	config
	hooks    []Hook
	mutation *ProductVideoMutation
}

// Where appends a list predicates to the ProductVideoDelete builder.
func (pvd *ProductVideoDelete) Where(ps ...predicate.ProductVideo) *ProductVideoDelete {
	pvd.mutation.Where(ps...)
	return pvd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (pvd *ProductVideoDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, pvd.sqlExec, pvd.mutation, pvd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (pvd *ProductVideoDelete) ExecX(ctx context.Context) int {
	n, err := pvd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (pvd *ProductVideoDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(productvideo.Table, sqlgraph.NewFieldSpec(productvideo.FieldID, field.TypeInt))
	if ps := pvd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, pvd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	pvd.mutation.done = true
	return affected, err
}

// ProductVideoDeleteOne is the builder for deleting a single ProductVideo entity.
type ProductVideoDeleteOne struct {
	pvd *ProductVideoDelete
}

// Where appends a list predicates to the ProductVideoDelete builder.
func (pvdo *ProductVideoDeleteOne) Where(ps ...predicate.ProductVideo) *ProductVideoDeleteOne {
	pvdo.pvd.mutation.Where(ps...)
	return pvdo
}

// Exec executes the deletion query.
func (pvdo *ProductVideoDeleteOne) Exec(ctx context.Context) error {
	n, err := pvdo.pvd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{productvideo.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (pvdo *ProductVideoDeleteOne) ExecX(ctx context.Context) {
	if err := pvdo.Exec(ctx); err != nil {
		panic(err)
	}
}
