// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kvngho/vimeovideoconverter/internal/infrastructure/persistence/ent/productreview"
)

// ProductReviewCreate is the builder for creating a ProductReview entity.
type ProductReviewCreate struct {
	config
	mutation *ProductReviewMutation
	hooks    []Hook
}

// SetPlayableVideo sets the "playable_video" field.
func (prc *ProductReviewCreate) SetPlayableVideo(s string) *ProductReviewCreate {
	prc.mutation.SetPlayableVideo(s)
	return prc
}

// SetReviewVideo sets the "review_video" field.
func (prc *ProductReviewCreate) SetReviewVideo(s string) *ProductReviewCreate {
	prc.mutation.SetReviewVideo(s)
	return prc
}

// Mutation returns the ProductReviewMutation object of the builder.
func (prc *ProductReviewCreate) Mutation() *ProductReviewMutation {
	return prc.mutation
}

// Save creates the ProductReview in the database.
func (prc *ProductReviewCreate) Save(ctx context.Context) (*ProductReview, error) {
	return withHooks(ctx, prc.sqlSave, prc.mutation, prc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (prc *ProductReviewCreate) SaveX(ctx context.Context) *ProductReview {
	v, err := prc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (prc *ProductReviewCreate) Exec(ctx context.Context) error {
	_, err := prc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (prc *ProductReviewCreate) ExecX(ctx context.Context) {
	if err := prc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (prc *ProductReviewCreate) check() error {
	if _, ok := prc.mutation.PlayableVideo(); !ok {
		return &ValidationError{Name: "playable_video", err: errors.New(`ent: missing required field "ProductReview.playable_video"`)}
	}
	if _, ok := prc.mutation.ReviewVideo(); !ok {
		return &ValidationError{Name: "review_video", err: errors.New(`ent: missing required field "ProductReview.review_video"`)}
	}
	return nil
}

func (prc *ProductReviewCreate) sqlSave(ctx context.Context) (*ProductReview, error) {
	if err := prc.check(); err != nil {
		return nil, err
	}
	_node, _spec := prc.createSpec()
	if err := sqlgraph.CreateNode(ctx, prc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	prc.mutation.id = &_node.ID
	prc.mutation.done = true
	return _node, nil
}

func (prc *ProductReviewCreate) createSpec() (*ProductReview, *sqlgraph.CreateSpec) {
	var (
		_node = &ProductReview{config: prc.config}
		_spec = sqlgraph.NewCreateSpec(productreview.Table, sqlgraph.NewFieldSpec(productreview.FieldID, field.TypeInt))
	)
	if value, ok := prc.mutation.PlayableVideo(); ok {
		_spec.SetField(productreview.FieldPlayableVideo, field.TypeString, value)
		_node.PlayableVideo = value
	}
	if value, ok := prc.mutation.ReviewVideo(); ok {
		_spec.SetField(productreview.FieldReviewVideo, field.TypeString, value)
		_node.ReviewVideo = value
	}
	return _node, _spec
}

// ProductReviewCreateBulk is the builder for creating many ProductReview entities in bulk.
type ProductReviewCreateBulk struct {
	config
	err      error
	builders []*ProductReviewCreate
}

// Save creates the ProductReview entities in the database.
func (prcb *ProductReviewCreateBulk) Save(ctx context.Context) ([]*ProductReview, error) {
	if prcb.err != nil {
		return nil, prcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(prcb.builders))
	nodes := make([]*ProductReview, len(prcb.builders))
	mutators := make([]Mutator, len(prcb.builders))
	for i := range prcb.builders {
		func(i int, root context.Context) {
			builder := prcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProductReviewMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, prcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, prcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, prcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (prcb *ProductReviewCreateBulk) SaveX(ctx context.Context) []*ProductReview {
	v, err := prcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (prcb *ProductReviewCreateBulk) Exec(ctx context.Context) error {
	_, err := prcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (prcb *ProductReviewCreateBulk) ExecX(ctx context.Context) {
	if err := prcb.Exec(ctx); err != nil {
		panic(err)
	}
}
