// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/kvngho/vimeovideoconverter/internal/infrastructure/persistence/ent/schema"
	"github.com/kvngho/vimeovideoconverter/internal/infrastructure/persistence/ent/uservideo"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	uservideoFields := schema.UserVideo{}.Fields()
	_ = uservideoFields
	// uservideoDescVideoID is the schema descriptor for video_id field.
	uservideoDescVideoID := uservideoFields[0].Descriptor()
	// uservideo.VideoIDValidator is a validator for the "video_id" field. It is called by the builders before save.
	uservideo.VideoIDValidator = uservideoDescVideoID.Validators[0].(func(int) error)
}
