// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kvngho/vimeovideoconverter/internal/infrastructure/persistence/ent/predicate"
	"github.com/kvngho/vimeovideoconverter/internal/infrastructure/persistence/ent/uservideo"
)

// UserVideoQuery is the builder for querying UserVideo entities.
type UserVideoQuery struct {
	config
	ctx        *QueryContext
	order      []uservideo.OrderOption
	inters     []Interceptor
	predicates []predicate.UserVideo
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UserVideoQuery builder.
func (uvq *UserVideoQuery) Where(ps ...predicate.UserVideo) *UserVideoQuery {
	uvq.predicates = append(uvq.predicates, ps...)
	return uvq
}

// Limit the number of records to be returned by this query.
func (uvq *UserVideoQuery) Limit(limit int) *UserVideoQuery {
	uvq.ctx.Limit = &limit
	return uvq
}

// Offset to start from.
func (uvq *UserVideoQuery) Offset(offset int) *UserVideoQuery {
	uvq.ctx.Offset = &offset
	return uvq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (uvq *UserVideoQuery) Unique(unique bool) *UserVideoQuery {
	uvq.ctx.Unique = &unique
	return uvq
}

// Order specifies how the records should be ordered.
func (uvq *UserVideoQuery) Order(o ...uservideo.OrderOption) *UserVideoQuery {
	uvq.order = append(uvq.order, o...)
	return uvq
}

// First returns the first UserVideo entity from the query.
// Returns a *NotFoundError when no UserVideo was found.
func (uvq *UserVideoQuery) First(ctx context.Context) (*UserVideo, error) {
	nodes, err := uvq.Limit(1).All(setContextOp(ctx, uvq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{uservideo.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (uvq *UserVideoQuery) FirstX(ctx context.Context) *UserVideo {
	node, err := uvq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UserVideo ID from the query.
// Returns a *NotFoundError when no UserVideo ID was found.
func (uvq *UserVideoQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = uvq.Limit(1).IDs(setContextOp(ctx, uvq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{uservideo.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (uvq *UserVideoQuery) FirstIDX(ctx context.Context) int {
	id, err := uvq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UserVideo entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UserVideo entity is found.
// Returns a *NotFoundError when no UserVideo entities are found.
func (uvq *UserVideoQuery) Only(ctx context.Context) (*UserVideo, error) {
	nodes, err := uvq.Limit(2).All(setContextOp(ctx, uvq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{uservideo.Label}
	default:
		return nil, &NotSingularError{uservideo.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (uvq *UserVideoQuery) OnlyX(ctx context.Context) *UserVideo {
	node, err := uvq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UserVideo ID in the query.
// Returns a *NotSingularError when more than one UserVideo ID is found.
// Returns a *NotFoundError when no entities are found.
func (uvq *UserVideoQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = uvq.Limit(2).IDs(setContextOp(ctx, uvq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{uservideo.Label}
	default:
		err = &NotSingularError{uservideo.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (uvq *UserVideoQuery) OnlyIDX(ctx context.Context) int {
	id, err := uvq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UserVideos.
func (uvq *UserVideoQuery) All(ctx context.Context) ([]*UserVideo, error) {
	ctx = setContextOp(ctx, uvq.ctx, ent.OpQueryAll)
	if err := uvq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*UserVideo, *UserVideoQuery]()
	return withInterceptors[[]*UserVideo](ctx, uvq, qr, uvq.inters)
}

// AllX is like All, but panics if an error occurs.
func (uvq *UserVideoQuery) AllX(ctx context.Context) []*UserVideo {
	nodes, err := uvq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UserVideo IDs.
func (uvq *UserVideoQuery) IDs(ctx context.Context) (ids []int, err error) {
	if uvq.ctx.Unique == nil && uvq.path != nil {
		uvq.Unique(true)
	}
	ctx = setContextOp(ctx, uvq.ctx, ent.OpQueryIDs)
	if err = uvq.Select(uservideo.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (uvq *UserVideoQuery) IDsX(ctx context.Context) []int {
	ids, err := uvq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (uvq *UserVideoQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, uvq.ctx, ent.OpQueryCount)
	if err := uvq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, uvq, querierCount[*UserVideoQuery](), uvq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (uvq *UserVideoQuery) CountX(ctx context.Context) int {
	count, err := uvq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (uvq *UserVideoQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, uvq.ctx, ent.OpQueryExist)
	switch _, err := uvq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (uvq *UserVideoQuery) ExistX(ctx context.Context) bool {
	exist, err := uvq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UserVideoQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (uvq *UserVideoQuery) Clone() *UserVideoQuery {
	if uvq == nil {
		return nil
	}
	return &UserVideoQuery{
		config:     uvq.config,
		ctx:        uvq.ctx.Clone(),
		order:      append([]uservideo.OrderOption{}, uvq.order...),
		inters:     append([]Interceptor{}, uvq.inters...),
		predicates: append([]predicate.UserVideo{}, uvq.predicates...),
		// clone intermediate query.
		sql:  uvq.sql.Clone(),
		path: uvq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		VideoID int `json:"video_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UserVideo.Query().
//		GroupBy(uservideo.FieldVideoID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (uvq *UserVideoQuery) GroupBy(field string, fields ...string) *UserVideoGroupBy {
	uvq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &UserVideoGroupBy{build: uvq}
	grbuild.flds = &uvq.ctx.Fields
	grbuild.label = uservideo.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		VideoID int `json:"video_id,omitempty"`
//	}
//
//	client.UserVideo.Query().
//		Select(uservideo.FieldVideoID).
//		Scan(ctx, &v)
func (uvq *UserVideoQuery) Select(fields ...string) *UserVideoSelect {
	uvq.ctx.Fields = append(uvq.ctx.Fields, fields...)
	sbuild := &UserVideoSelect{UserVideoQuery: uvq}
	sbuild.label = uservideo.Label
	sbuild.flds, sbuild.scan = &uvq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a UserVideoSelect configured with the given aggregations.
func (uvq *UserVideoQuery) Aggregate(fns ...AggregateFunc) *UserVideoSelect {
	return uvq.Select().Aggregate(fns...)
}

func (uvq *UserVideoQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range uvq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, uvq); err != nil {
				return err
			}
		}
	}
	for _, f := range uvq.ctx.Fields {
		if !uservideo.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if uvq.path != nil {
		prev, err := uvq.path(ctx)
		if err != nil {
			return err
		}
		uvq.sql = prev
	}
	return nil
}

func (uvq *UserVideoQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*UserVideo, error) {
	var (
		nodes = []*UserVideo{}
		_spec = uvq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*UserVideo).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &UserVideo{config: uvq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, uvq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (uvq *UserVideoQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := uvq.querySpec()
	_spec.Node.Columns = uvq.ctx.Fields
	if len(uvq.ctx.Fields) > 0 {
		_spec.Unique = uvq.ctx.Unique != nil && *uvq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, uvq.driver, _spec)
}

func (uvq *UserVideoQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(uservideo.Table, uservideo.Columns, sqlgraph.NewFieldSpec(uservideo.FieldID, field.TypeInt))
	_spec.From = uvq.sql
	if unique := uvq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if uvq.path != nil {
		_spec.Unique = true
	}
	if fields := uvq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, uservideo.FieldID)
		for i := range fields {
			if fields[i] != uservideo.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := uvq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := uvq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := uvq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := uvq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (uvq *UserVideoQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(uvq.driver.Dialect())
	t1 := builder.Table(uservideo.Table)
	columns := uvq.ctx.Fields
	if len(columns) == 0 {
		columns = uservideo.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if uvq.sql != nil {
		selector = uvq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if uvq.ctx.Unique != nil && *uvq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range uvq.predicates {
		p(selector)
	}
	for _, p := range uvq.order {
		p(selector)
	}
	if offset := uvq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := uvq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UserVideoGroupBy is the group-by builder for UserVideo entities.
type UserVideoGroupBy struct {
	selector
	build *UserVideoQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (uvgb *UserVideoGroupBy) Aggregate(fns ...AggregateFunc) *UserVideoGroupBy {
	uvgb.fns = append(uvgb.fns, fns...)
	return uvgb
}

// Scan applies the selector query and scans the result into the given value.
func (uvgb *UserVideoGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, uvgb.build.ctx, ent.OpQueryGroupBy)
	if err := uvgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserVideoQuery, *UserVideoGroupBy](ctx, uvgb.build, uvgb, uvgb.build.inters, v)
}

func (uvgb *UserVideoGroupBy) sqlScan(ctx context.Context, root *UserVideoQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(uvgb.fns))
	for _, fn := range uvgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*uvgb.flds)+len(uvgb.fns))
		for _, f := range *uvgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*uvgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := uvgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// UserVideoSelect is the builder for selecting fields of UserVideo entities.
type UserVideoSelect struct {
	*UserVideoQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (uvs *UserVideoSelect) Aggregate(fns ...AggregateFunc) *UserVideoSelect {
	uvs.fns = append(uvs.fns, fns...)
	return uvs
}

// Scan applies the selector query and scans the result into the given value.
func (uvs *UserVideoSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, uvs.ctx, ent.OpQuerySelect)
	if err := uvs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserVideoQuery, *UserVideoSelect](ctx, uvs.UserVideoQuery, uvs, uvs.inters, v)
}

func (uvs *UserVideoSelect) sqlScan(ctx context.Context, root *UserVideoQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(uvs.fns))
	for _, fn := range uvs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*uvs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := uvs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
