// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kvngho/vimeovideoconverter/internal/infrastructure/persistence/ent/predicate"
	"github.com/kvngho/vimeovideoconverter/internal/infrastructure/persistence/ent/uservideo"
)

// UserVideoDelete is the builder for deleting a UserVideo entity.
type UserVideoDelete struct {
	config
	hooks    []Hook
	mutation *UserVideoMutation
}

// Where appends a list predicates to the UserVideoDelete builder.
func (uvd *UserVideoDelete) Where(ps ...predicate.UserVideo) *UserVideoDelete {
	uvd.mutation.Where(ps...)
	return uvd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (uvd *UserVideoDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, uvd.sqlExec, uvd.mutation, uvd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (uvd *UserVideoDelete) ExecX(ctx context.Context) int {
	n, err := uvd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (uvd *UserVideoDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(uservideo.Table, sqlgraph.NewFieldSpec(uservideo.FieldID, field.TypeInt))
	if ps := uvd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, uvd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	uvd.mutation.done = true
	return affected, err
}

// UserVideoDeleteOne is the builder for deleting a single UserVideo entity.
type UserVideoDeleteOne struct {
	uvd *UserVideoDelete
}

// Where appends a list predicates to the UserVideoDelete builder.
func (uvdo *UserVideoDeleteOne) Where(ps ...predicate.UserVideo) *UserVideoDeleteOne {
	uvdo.uvd.mutation.Where(ps...)
	return uvdo
}

// Exec executes the deletion query.
func (uvdo *UserVideoDeleteOne) Exec(ctx context.Context) error {
	n, err := uvdo.uvd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{uservideo.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (uvdo *UserVideoDeleteOne) ExecX(ctx context.Context) {
	if err := uvdo.Exec(ctx); err != nil {
		panic(err)
	}
}
