// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// DeepingTalk is the predicate function for deepingtalk builders.
type DeepingTalk func(*sql.Selector)

// ProductReview is the predicate function for productreview builders.
type ProductReview func(*sql.Selector)

// ProductVideo is the predicate function for productvideo builders.
type ProductVideo func(*sql.Selector)

// UserVideo is the predicate function for uservideo builders.
type UserVideo func(*sql.Selector)
