// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ProductVideo is the predicate function for productvideo builders.
type ProductVideo func(*sql.Selector)

// UserVideo is the predicate function for uservideo builders.
type UserVideo func(*sql.Selector)
